name: blue_tooth_wifi_pair_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter
  flutter_blue_plus: 1.32.8
  go_router: ^14.2.1
  mobile_scanner: ^5.1.1
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  wifi_scan: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
